#!/usr/bin/env python3

import os
import sys

MODULES = [("pitivi", None),
           ("GStreamer", "gstreamer (core)"),
           ("GStreamer", "gst-plugins-base"),
           ("GStreamer", "gst-plugins-good"),
           ("GStreamer", "gst-plugins-ugly"),
           ("GStreamer", "gst-plugins-bad"),
           ("GStreamer", "gst-libav"),
           ("GStreamer", "gst-devtools"),
           ("GStreamer", "gst-editing-services")]

if len(sys.argv) > 1:
    MODULES = sys.argv[1:]

os.system(" ./add_user.php bugzilla_import gstreamer.bugzilla.import@gmail.com 'GStreamer bugzilla importer' thiblahute")
for c, m in MODULES:
    cm = c
    if m:
        cm += "/%s" % m
    else:
        m = c

    print("Downloading XML file for %s" % m)
    if os.system("./downloadbzbugs '%s' 'outfiles/%s.xml'" % (cm, m)) != 0:
        print("%s failed downloading" % m)
        exit(1)

    print("Adding users for %s" % m)
    if os.system("./bzuserstophab 'outfiles/%s.xml' bugzilla_import" % (m)) != 0:
        print("%s failed adding users" % m)
        exit(1)

    print("Generating JSON for '%s'" % m)
    if os.system("./bzxmltophill 'outfiles/%s.xml'" % (m)) != 0:
        print("%s failed converting to json" % m)
        exit(1)

    try:
        os.mkdir(os.path.join("outfiles", m))
    except:
        pass

    print("Importing bugs %s" % m)
    if os.system("./phill.php --input 'outfiles/%s.json' -v 2 > 'outfiles/%s/phill_%s.logs' 2>&1" % (m, m, m)) != 0:
        print("%s failed to import bugs into phabricator" % m)
        exit(1)
